### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by Daniellop1** [nates/DiscordVerification#9]
Hi, I was trying to start the bot using the node index command but I got this error, can someone help me?

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/sandbox/node_modules/express/lib/application.js:618:24)
    at Object.main [as run] (/sandbox/server.js:45:7)
    at Object.<anonymous> (/sandbox/index.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by nates** [comment]
Change the port, it is being used.
